version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    tty: true
    restart: always
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_USER: "user"
      MSSQL_PASSWORD: "SqlServer2019!"
    ports:
      - "1433:1433"